import type { Lesson, World } from "./types";

const standardReward = { xp: 10, coins: 5, stars: 1 } as const;

const lessons: Lesson[] = [
  {
    id: "hello",
    title: "Hello!",
    titleJa: "あいさつ",
    icon: "👋",
    kind: "normal",
    items: [
      "hello", "good-morning", "goodbye", "whats-your-name", "my-name-is-kiko",
      "how-are-you", "im-happy", "im-tired",
    ],
    questions: [
      { type: "listen-picture", target: "hello", choices: ["hello", "good-morning", "im-tired"] },
      { type: "listen-picture", target: "goodbye", choices: ["goodbye", "good-morning", "im-happy"] },
      { type: "picture-word", target: "im-happy", choices: ["im-happy", "im-tired", "good-morning"] },
      { type: "picture-word", target: "good-morning", choices: ["good-morning", "hello", "goodbye"] },
      { type: "sentence-builder", target: "my-name-is-kiko" },
      { type: "sentence-builder", target: "whats-your-name" },
      { type: "speak", target: "how-are-you" },
    ],
    reward: standardReward,
  },
  {
    id: "colors",
    title: "Colors",
    titleJa: "いろ",
    icon: "🎨",
    kind: "normal",
    items: ["red", "blue", "yellow", "green", "pink", "purple", "black", "white", "its-red", "its-blue"],
    questions: [
      { type: "listen-picture", target: "red", choices: ["red", "blue", "yellow"] },
      { type: "listen-picture", target: "green", choices: ["green", "pink", "black"] },
      { type: "picture-word", target: "blue", choices: ["blue", "purple", "white"] },
      { type: "picture-word", target: "yellow", choices: ["yellow", "pink", "black"] },
      { type: "sentence-builder", target: "its-red" },
      { type: "sentence-builder", target: "its-blue" },
      { type: "speak", target: "purple" },
    ],
    reward: standardReward,
  },
  {
    id: "animals",
    title: "Animals",
    titleJa: "どうぶつ",
    icon: "🐾",
    kind: "normal",
    items: ["cat", "dog", "bird", "rabbit", "fish", "tiger", "its-a-cat", "its-a-dog"],
    questions: [
      { type: "listen-picture", target: "cat", choices: ["cat", "dog", "fish"] },
      { type: "listen-picture", target: "rabbit", choices: ["rabbit", "bird", "tiger"] },
      { type: "picture-word", target: "dog", choices: ["dog", "cat", "bird"] },
      { type: "picture-word", target: "fish", choices: ["fish", "rabbit", "tiger"] },
      { type: "sentence-builder", target: "its-a-cat" },
      { type: "sentence-builder", target: "its-a-dog" },
      { type: "speak", target: "tiger" },
    ],
    reward: standardReward,
  },
  {
    id: "numbers",
    title: "Numbers",
    titleJa: "かず",
    icon: "🔢",
    kind: "normal",
    items: [
      "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
      "one-cat", "two-dogs", "three-birds",
    ],
    questions: [
      { type: "listen-picture", target: "one", choices: ["one", "two", "three"] },
      { type: "listen-picture", target: "five", choices: ["five", "six", "eight"] },
      { type: "picture-word", target: "three", choices: ["three", "four", "seven"] },
      { type: "picture-word", target: "ten", choices: ["ten", "nine", "two"] },
      { type: "sentence-builder", target: "one-cat" },
      { type: "sentence-builder", target: "two-dogs" },
      { type: "sentence-builder", target: "three-birds" },
    ],
    reward: standardReward,
  },
  {
    id: "food",
    title: "Food",
    titleJa: "たべもの",
    icon: "🍎",
    kind: "normal",
    items: ["apple", "banana", "pizza", "rice", "bread", "ice-cream", "its-an-apple", "its-pizza"],
    questions: [
      { type: "listen-picture", target: "apple", choices: ["apple", "banana", "bread"] },
      { type: "listen-picture", target: "pizza", choices: ["pizza", "rice", "ice-cream"] },
      { type: "picture-word", target: "banana", choices: ["banana", "apple", "rice"] },
      { type: "picture-word", target: "bread", choices: ["bread", "pizza", "ice-cream"] },
      { type: "sentence-builder", target: "its-an-apple" },
      { type: "sentence-builder", target: "its-pizza" },
      { type: "speak", target: "ice-cream" },
    ],
    reward: standardReward,
  },
  {
    id: "i-like",
    title: "I like...",
    titleJa: "すきなもの",
    icon: "❤️",
    kind: "normal",
    items: ["i-like-cats", "i-like-pizza", "i-like-blue", "i-like-dogs", "i-like-apples", "i-like-red"],
    questions: [
      { type: "listen-picture", target: "i-like-cats", choices: ["i-like-cats", "i-like-pizza", "i-like-blue"] },
      { type: "listen-picture", target: "i-like-red", choices: ["i-like-red", "i-like-dogs", "i-like-apples"] },
      { type: "picture-word", target: "i-like-pizza", choices: ["i-like-pizza", "i-like-cats", "i-like-red"] },
      { type: "picture-word", target: "i-like-blue", choices: ["i-like-blue", "i-like-apples", "i-like-dogs"] },
      { type: "sentence-builder", target: "i-like-cats" },
      { type: "sentence-builder", target: "i-like-pizza" },
      { type: "speak", target: "i-like-blue" },
    ],
    reward: standardReward,
  },
  {
    id: "do-you-like",
    title: "Do you like...?",
    titleJa: "すきですか？",
    icon: "❓",
    kind: "normal",
    items: ["do-you-like-cats", "do-you-like-pizza", "do-you-like-blue", "yes-i-do", "no-i-dont"],
    questions: [
      { type: "listen-picture", target: "yes-i-do", choices: ["yes-i-do", "no-i-dont", "do-you-like-cats"] },
      { type: "listen-picture", target: "do-you-like-pizza", choices: ["do-you-like-pizza", "do-you-like-cats", "yes-i-do"] },
      { type: "picture-word", target: "no-i-dont", choices: ["no-i-dont", "yes-i-do", "do-you-like-blue"] },
      { type: "picture-word", target: "do-you-like-cats", choices: ["do-you-like-cats", "do-you-like-pizza", "yes-i-do"] },
      { type: "sentence-builder", target: "do-you-like-cats" },
      { type: "sentence-builder", target: "yes-i-do" },
      { type: "speak", target: "no-i-dont" },
    ],
    reward: standardReward,
  },
  {
    id: "family",
    title: "My Family",
    titleJa: "かぞく",
    icon: "🏠",
    kind: "normal",
    items: [
      "mom", "dad", "brother", "sister", "grandma", "grandpa",
      "this-is-my-mom", "this-is-my-dad", "i-have-a-brother",
    ],
    questions: [
      { type: "listen-picture", target: "mom", choices: ["mom", "dad", "grandpa"] },
      { type: "listen-picture", target: "sister", choices: ["sister", "brother", "grandma"] },
      { type: "picture-word", target: "dad", choices: ["dad", "mom", "brother"] },
      { type: "picture-word", target: "grandma", choices: ["grandma", "grandpa", "sister"] },
      { type: "sentence-builder", target: "this-is-my-mom" },
      { type: "sentence-builder", target: "this-is-my-dad" },
      { type: "speak", target: "i-have-a-brother" },
    ],
    reward: standardReward,
  },
  {
    id: "review",
    title: "Review",
    titleJa: "ふくしゅう",
    icon: "✨",
    kind: "review",
    items: [],
    generate: {
      fromLessons: ["hello", "colors", "animals", "numbers", "food", "i-like", "do-you-like", "family"],
      count: 8,
      types: ["listen-picture", "picture-word", "sentence-builder"],
    },
    reward: standardReward,
  },
  {
    id: "boss",
    title: "Boss Lesson",
    titleJa: "クイズモンスター",
    icon: "🏆",
    kind: "boss",
    items: [],
    generate: {
      fromLessons: ["hello", "colors", "animals", "numbers", "food", "i-like", "do-you-like", "family"],
      count: 9,
      types: ["listen-picture", "picture-word", "sentence-builder"],
    },
    reward: { xp: 30, coins: 20, stars: 1 },
  },
];

export const world: World = {
  id: "my-english-adventure",
  title: "My English Adventure",
  lessons,
  milestones: [
    { id: "animals-treasure", afterLesson: "animals", icon: "🎁", reward: { coins: 10 } },
  ],
};
